# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-05-03 08:17+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: core/Rpg.py:53
msgid "ERROR_UNKNOWN_SELECTED_WORLD"
msgstr ""

#: core/Rpg.py:60
msgid "ERROR_NO_SELECTED_PLAYER"
msgstr ""

#: core/Rpg.py:84
msgid "PLAYER_SELECTION"
msgstr ""

#: core/Rpg.py:85
msgid "CHOICE_NEW_PLAYER"
msgstr ""

#: core/Rpg.py:86
msgid "CHOICE_EXISTING_PLAYER"
msgstr ""

#: core/Rpg.py:89
msgid "CHOICE_QUESTION"
msgstr ""

#: core/Rpg.py:110 core/commands/createPlayer.py:46
msgid "LOGIN_PROMPT"
msgstr ""

#: core/Rpg.py:113 core/commands/createPlayer.py:54
msgid "PASSWORD_PROMPT"
msgstr ""

#: core/Rpg.py:222
msgid "COMMAND_PROMPT"
msgstr ""

#: core/command_factory.py:39 core/commands/help.py:38
#: tests/commands/testHelp.py:26 tests/commands/testHelp.py:61
#: tests/commands/testLook.py:15 tests/commands/testLook.py:39
msgid "LOOK_COMMAND"
msgstr ""

#: core/command_factory.py:40 core/commands/help.py:22
#: tests/commands/testHelp.py:18 tests/commands/testHelp.py:45
#: tests/commands/testTalk.py:14 tests/commands/testTalk.py:19
#: tests/commands/testTalk.py:24 tests/commands/testTalk.py:29
#: tests/commands/testTalk.py:34 tests/commands/testTalk.py:39
#: tests/commands/testTalk.py:44 tests/commands/testTalk.py:49
#: tests/commands/testTalk.py:54
msgid "TALK_COMMAND"
msgstr ""

#: core/command_factory.py:41 core/commands/help.py:26
#: tests/commands/testHelp.py:20 tests/commands/testHelp.py:49
#: tests/commands/testMove.py:14 tests/commands/testMove.py:19
#: tests/commands/testMove.py:24 tests/commands/testMove.py:29
#: tests/commands/testMove.py:34 tests/commands/testMove.py:39
#: tests/commands/testMove.py:44 tests/commands/testMove.py:49
msgid "MOVE_COMMAND"
msgstr ""

#: core/command_factory.py:42 core/commands/help.py:30
#: tests/commands/testEnter.py:14 tests/commands/testEnter.py:19
#: tests/commands/testEnter.py:24 tests/commands/testEnter.py:29
#: tests/commands/testEnter.py:34 tests/commands/testEnter.py:39
#: tests/commands/testEnter.py:44 tests/commands/testEnter.py:46
#: tests/commands/testEnter.py:51 tests/commands/testEnter.py:53
#: tests/commands/testEnter.py:58 tests/commands/testEnter.py:63
#: tests/commands/testExit.py:53 tests/commands/testExit.py:60
#: tests/commands/testHelp.py:22 tests/commands/testHelp.py:53
msgid "ENTER_COMMAND"
msgstr ""

#: core/command_factory.py:43 core/commands/help.py:34
#: tests/commands/testExit.py:13 tests/commands/testExit.py:18
#: tests/commands/testExit.py:23 tests/commands/testExit.py:28
#: tests/commands/testExit.py:33 tests/commands/testExit.py:38
#: tests/commands/testExit.py:43 tests/commands/testExit.py:48
#: tests/commands/testExit.py:55 tests/commands/testExit.py:62
#: tests/commands/testHelp.py:24 tests/commands/testHelp.py:57
msgid "EXIT_COMMAND"
msgstr ""

#: core/command_factory.py:44 core/commands/help.py:46
#: tests/commands/testDrop.py:54 tests/commands/testDrop.py:62
#: tests/commands/testDrop.py:69 tests/commands/testDrop.py:77
#: tests/commands/testDrop.py:84 tests/commands/testDrop.py:92
#: tests/commands/testHelp.py:30 tests/commands/testHelp.py:69
#: tests/commands/testInventory.py:24 tests/commands/testInventory.py:32
#: tests/commands/testTake.py:14 tests/commands/testTake.py:19
#: tests/commands/testTake.py:24 tests/commands/testTake.py:29
#: tests/commands/testTake.py:34 tests/commands/testTake.py:39
#: tests/commands/testTake.py:44 tests/commands/testTake.py:49
#: tests/commands/testTake.py:54 tests/commands/testTake.py:59
#: tests/commands/testTake.py:64 tests/commands/testTake.py:69
#: tests/commands/testTake.py:74 tests/commands/testTake.py:79
msgid "TAKE_COMMAND"
msgstr ""

#: core/command_factory.py:45 core/commands/help.py:50
#: tests/commands/testDrop.py:14 tests/commands/testDrop.py:19
#: tests/commands/testDrop.py:24 tests/commands/testDrop.py:29
#: tests/commands/testDrop.py:34 tests/commands/testDrop.py:39
#: tests/commands/testDrop.py:44 tests/commands/testDrop.py:49
#: tests/commands/testDrop.py:56 tests/commands/testDrop.py:64
#: tests/commands/testDrop.py:71 tests/commands/testDrop.py:79
#: tests/commands/testDrop.py:86 tests/commands/testDrop.py:94
#: tests/commands/testHelp.py:32 tests/commands/testHelp.py:73
msgid "DROP_COMMAND"
msgstr ""

#: core/command_factory.py:46 core/commands/help.py:42
#: tests/commands/testHelp.py:28 tests/commands/testHelp.py:65
#: tests/commands/testInventory.py:14 tests/commands/testInventory.py:19
#: tests/commands/testInventory.py:26 tests/commands/testInventory.py:34
msgid "INVENTORY_COMMAND"
msgstr ""

#: core/command_factory.py:47 core/commands/help.py:42
#: tests/commands/testHelp.py:28 tests/commands/testHelp.py:65
msgid "INVENTORY_SHORT_COMMAND"
msgstr ""

#: core/command_factory.py:48 core/commands/help.py:54
#: tests/commands/testHelp.py:15 tests/commands/testHelp.py:34
#: tests/commands/testHelp.py:41 tests/commands/testHelp.py:77
msgid "HELP_COMMAND"
msgstr ""

#: core/command_factory.py:49 tests/commands/testOpen.py:14
#: tests/commands/testOpen.py:19 tests/commands/testOpen.py:24
#: tests/commands/testOpen.py:29 tests/commands/testOpen.py:34
#: tests/commands/testOpen.py:39 tests/commands/testOpen.py:44
#: tests/commands/testOpen.py:49 tests/commands/testOpen.py:54
#: tests/commands/testOpen.py:63 tests/commands/testOpen.py:68
#: tests/commands/testOpen.py:72 tests/commands/testOpen.py:80
#: tests/commands/testOpen.py:84 tests/commands/testOpen.py:92
#: tests/commands/testOpen.py:101 tests/commands/testOpen.py:105
#: tests/commands/testOpen.py:109 tests/commands/testOpen.py:113
#: tests/commands/testOpen.py:117
msgid "OPEN_COMMAND"
msgstr ""

#: core/command_factory.py:75 core/commands/help.py:58
#: tests/commands/testHelp.py:36 tests/commands/testHelp.py:81
msgid "QUIT_COMMAND"
msgstr ""

#: core/command_factory.py:75 core/commands/help.py:58
#: tests/commands/testHelp.py:36 tests/commands/testHelp.py:81
msgid "QUIT_SHORT_COMMAND"
msgstr ""

#: core/command_factory.py:84 core/command_factory.py:97
msgid "ERROR_UNKNOWN_COMMAND"
msgstr ""

#: core/commands/createPlayer.py:23 tests/commands/testCreatePlayer.py:19
#: tests/commands/testCreatePlayer.py:24
msgid "ERROR_SIGNUP_NOT_ENOUGH_ARGUMENTS"
msgstr ""

#: core/commands/createPlayer.py:28 core/commands/createPlayer.py:49
#: tests/commands/testCreatePlayer.py:29 tests/commands/testCreatePlayer.py:34
msgid "ERROR_SIGNUP_LOGIN_ALREADY_USED"
msgstr ""

#: core/commands/createPlayer.py:32 tests/commands/testCreatePlayer.py:39
#: tests/commands/testCreatePlayer.py:44
msgid "ERROR_SIGNUP_INVALID_GENDER"
msgstr ""

#: core/commands/createPlayer.py:36 tests/commands/testCreatePlayer.py:49
#: tests/commands/testCreatePlayer.py:54
msgid "ERROR_SIGNUP_INVALID_SPECIES"
msgstr ""

#: core/commands/createPlayer.py:55
msgid "CONFIRM_PASSWORD_PROMPT"
msgstr ""

#: core/commands/createPlayer.py:58
msgid "ERROR_SIGNUP_PASSWORDS"
msgstr ""

#: core/commands/createPlayer.py:64
msgid "GENDER_SELECTION"
msgstr ""

#: core/commands/createPlayer.py:70
msgid "GENDER_PROMPT"
msgstr ""

#: core/commands/createPlayer.py:84
msgid "SPECIES_SELECTION"
msgstr ""

#: core/commands/createPlayer.py:91
msgid "SPECIES_PROMPT"
msgstr ""

#: core/commands/createPlayer.py:104 tests/commands/testCreatePlayer.py:59
msgid "PLAYER_CREATION_CONFIRMATION"
msgstr ""

#: core/commands/drop.py:20 tests/commands/testDrop.py:16
#: tests/commands/testDrop.py:21
msgid "ERROR_DROP_NO_ITEM_GIVEN"
msgstr ""

#: core/commands/drop.py:22 tests/commands/testDrop.py:46
#: tests/commands/testDrop.py:51
msgid "ERROR_DROP_INVALID_QUANTITY"
msgstr ""

#: core/commands/drop.py:36 tests/commands/testDrop.py:26
#: tests/commands/testDrop.py:31
msgid "ERROR_DROP_UNKNOWN_ITEM"
msgstr ""

#: core/commands/drop.py:41 tests/commands/testDrop.py:36
#: tests/commands/testDrop.py:41
msgid "ERROR_DROP_ITEM_NOT_AVAILABLE"
msgstr ""

#: core/commands/drop.py:43 tests/commands/testDrop.py:58
#: tests/commands/testDrop.py:66
#, python-format
msgid "ERROR_DROP_QUANTITY_TOO_HIGH_%s"
msgstr ""

#: core/commands/drop.py:57 tests/commands/testDrop.py:73
#: tests/commands/testDrop.py:88
#, python-format
msgid "DROP_CONFIRMATION_%(quantity)s_%(name)s"
msgstr ""

#: core/commands/enter.py:21 tests/commands/testEnter.py:16
#: tests/commands/testEnter.py:21
msgid "ERROR_ENTER_NO_PLACE_GIVEN"
msgstr ""

#: core/commands/enter.py:27 core/commands/exit.py:27
#: tests/commands/testEnter.py:26 tests/commands/testEnter.py:31
#: tests/commands/testEnter.py:48 tests/commands/testEnter.py:55
#: tests/commands/testExit.py:25 tests/commands/testExit.py:30
#: tests/commands/testExit.py:45 tests/commands/testExit.py:50
msgid "ERROR_ENTER_PLACE_NOT_AVAILABLE"
msgstr ""

#: core/commands/enter.py:32 tests/commands/testEnter.py:60
#: tests/commands/testEnter.py:65
msgid "ENTER_CONFIRMATION"
msgstr ""

#: core/commands/exit.py:21 tests/commands/testExit.py:15
#: tests/commands/testExit.py:20
msgid "ERROR_EXIT_NO_PLACE_GIVEN"
msgstr ""

#: core/commands/exit.py:30 tests/commands/testExit.py:57
#: tests/commands/testExit.py:64
msgid "EXIT_CONFIRMATION"
msgstr ""

#: core/commands/help.py:22 tests/commands/testHelp.py:18
#: tests/commands/testHelp.py:45
msgid "CHARACTER_TOKEN"
msgstr ""

#: core/commands/help.py:22 tests/commands/testHelp.py:18
#: tests/commands/testHelp.py:45
msgid "SENTENCE_TOKEN"
msgstr ""

#: core/commands/help.py:23 tests/commands/testHelp.py:19
#: tests/commands/testHelp.py:46
msgid "TALK_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:27 tests/commands/testHelp.py:21
#: tests/commands/testHelp.py:50
msgid "MOVE_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:31 tests/commands/testHelp.py:23
#: tests/commands/testHelp.py:54
msgid "ENTER_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:35 tests/commands/testHelp.py:25
#: tests/commands/testHelp.py:58
msgid "EXIT_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:39 tests/commands/testHelp.py:27
#: tests/commands/testHelp.py:62
msgid "LOOK_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:43 tests/commands/testHelp.py:29
#: tests/commands/testHelp.py:66
msgid "INVENTORY_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:46 core/commands/help.py:50
#: tests/commands/testHelp.py:30 tests/commands/testHelp.py:32
#: tests/commands/testHelp.py:69 tests/commands/testHelp.py:73
msgid "ITEM_NAME_TOKEN"
msgstr ""

#: core/commands/help.py:46 core/commands/help.py:50
#: tests/commands/testHelp.py:30 tests/commands/testHelp.py:32
#: tests/commands/testHelp.py:69 tests/commands/testHelp.py:73
msgid "QUANTITY_TOKEN"
msgstr ""

#: core/commands/help.py:47 tests/commands/testHelp.py:31
#: tests/commands/testHelp.py:70
msgid "TAKE_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:51 tests/commands/testHelp.py:33
#: tests/commands/testHelp.py:74
msgid "DROP_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:55 tests/commands/testHelp.py:35
#: tests/commands/testHelp.py:78
msgid "HELP_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:59 tests/commands/testHelp.py:37
#: tests/commands/testHelp.py:82
msgid "QUIT_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:64 tests/commands/testHelp.py:17
msgid "AVAILABLE_COMMANDS_TITLE"
msgstr ""

#: core/commands/look.py:70 tests/commands/testLook.py:18
#, python-format
msgid "CURRENT_REGION_%s"
msgstr ""

#: core/commands/look.py:74 tests/commands/testLook.py:20
msgid "PRESENT_CHARACTERS"
msgstr ""

#: core/commands/look.py:80 tests/commands/testLook.py:23
msgid "AVAILABLE_DIRECTIONS"
msgstr ""

#: core/commands/look.py:86 tests/commands/testLook.py:26
msgid "AVAILABLE_PLACES"
msgstr ""

#: core/commands/look.py:92 tests/commands/testLook.py:29
msgid "AVAILABLE_ITEMS"
msgstr ""

#: core/commands/look.py:98 tests/commands/testLook.py:32
msgid "AVAILABLE_ITEMS_CONTAINERS"
msgstr ""

#: core/commands/move.py:19 tests/commands/testMove.py:16
#: tests/commands/testMove.py:21
msgid "ERROR_MOVE_NO_DIRECTION_GIVEN"
msgstr ""

#: core/commands/move.py:23 tests/commands/testMove.py:26
#: tests/commands/testMove.py:31
#, python-format
msgid "ERROR_MOVE_INVALID_DIRECTION_%s"
msgstr ""

#: core/commands/move.py:30 tests/commands/testMove.py:36
#: tests/commands/testMove.py:41
msgid "ERROR_MOVE_DIRECTION_NOT_AVAILABLE"
msgstr ""

#: core/commands/move.py:37 tests/commands/testMove.py:46
#, python-format
msgid "MOVE_CONFIRMATION_%s"
msgstr ""

#: core/commands/open.py:17 tests/commands/testOpen.py:16
#: tests/commands/testOpen.py:21
msgid "ERROR_OPEN_NO_CONTAINER_PROVIDED"
msgstr ""

#: core/commands/open.py:42 tests/commands/testOpen.py:57
#: tests/commands/testOpen.py:75 tests/commands/testOpen.py:87
#: tests/commands/testOpen.py:95
#, python-format
msgid "ITEMS_IN_CONTAINER_%s"
msgstr ""

#: core/commands/take.py:15 tests/commands/testTake.py:16
#: tests/commands/testTake.py:21
msgid "ERROR_TAKE_NO_ITEM_GIVEN"
msgstr ""

#: core/commands/take.py:17 tests/commands/testTake.py:46
#: tests/commands/testTake.py:51
msgid "ERROR_TAKE_INVALID_QUANTITY"
msgstr ""

#: core/commands/take.py:23 tests/commands/testTake.py:26
#: tests/commands/testTake.py:31
msgid "ERROR_TAKE_UNKNOWN_ITEM"
msgstr ""

#: core/commands/take.py:39 tests/commands/testTake.py:36
#: tests/commands/testTake.py:41
msgid "ERROR_TAKE_ITEM_NOT_AVAILABLE"
msgstr ""

#: core/commands/take.py:42 tests/commands/testTake.py:56
#: tests/commands/testTake.py:61
msgid "ERROR_TAKE_QUANTITY_TOO_HIGH"
msgstr ""

#: core/commands/take.py:55 tests/commands/testTake.py:66
#: tests/commands/testTake.py:76
#, python-format
msgid "TAKE_CONFIRMATION_%(quantity)s_%(name)s"
msgstr ""

#: core/commands/talk.py:18 tests/commands/testTalk.py:16
#: tests/commands/testTalk.py:21
msgid "ERROR_TALK_NO_CHARACTER_GIVEN"
msgstr ""

#: core/commands/talk.py:20 tests/commands/testTalk.py:26
#: tests/commands/testTalk.py:31
msgid "ERROR_TALK_NO_SENTENCE_GIVEN"
msgstr ""

#: core/commands/talk.py:29 tests/commands/testTalk.py:36
#: tests/commands/testTalk.py:41
msgid "ERROR_TALK_UNKNOWN_CHARACTER"
msgstr ""

#: core/commands/talk.py:36 tests/commands/testTalk.py:46
msgid "ERROR_TALK_UNKNOWN_SENTENCE"
msgstr ""

#: models/area.py:21 tests/commands/testLook.py:24
#: tests/commands/testLook.py:42 tests/commands/testMove.py:44
#: tests/commands/testMove.py:46 tests/commands/testMove.py:49
#: tests/commands/testMove.py:51
msgid "DIRECTION_KEY_NORTH"
msgstr ""

#: models/area.py:22 tests/commands/testMove.py:34
#: tests/commands/testMove.py:39
msgid "DIRECTION_KEY_EAST"
msgstr ""

#: models/area.py:23
msgid "DIRECTION_KEY_SOUTH"
msgstr ""

#: models/area.py:24
msgid "DIRECTION_KEY_WEST"
msgstr ""

#: models/area.py:39
msgid "AREA_TYPE_DUNGEON"
msgstr ""

#: models/area.py:39
msgid "AREA_TYPE_LAND"
msgstr ""

#: models/item_container.py:32 tests/commands/testOpen.py:36
#: tests/commands/testOpen.py:41
msgid "ERROR_UNKNOWN_ITEM_CONTAINER_TYPE_LABEL"
msgstr ""

#: models/item_container.py:50
msgid "ERROR_INVALID_ITEM_CONTAINER_INDEX"
msgstr ""

#: models/item_container.py:53 tests/commands/testOpen.py:26
#: tests/commands/testOpen.py:31
msgid "ERROR_CONTAINER_NOT_AVAILABLE"
msgstr ""

#: models/item_container.py:55 tests/commands/testOpen.py:46
#: tests/commands/testOpen.py:51
msgid "ERROR_MULTIPLE_CONTAINERS_AVAILABLE"
msgstr ""

#: models/place.py:15 models/place.py:29 models/place.py:39 models/place.py:49
#: tests/commands/testEnter.py:24 tests/commands/testExit.py:23
#: tests/commands/testExit.py:28
msgid "PLACE_TYPE_CAVE"
msgstr ""

#: models/place.py:15 models/place.py:27 models/place.py:37 models/place.py:47
#: tests/commands/testEnter.py:44 tests/commands/testEnter.py:46
#: tests/commands/testEnter.py:51 tests/commands/testEnter.py:53
#: tests/commands/testEnter.py:58 tests/commands/testEnter.py:63
#: tests/commands/testExit.py:43 tests/commands/testExit.py:48
#: tests/commands/testExit.py:53 tests/commands/testExit.py:55
#: tests/commands/testExit.py:60 tests/commands/testExit.py:62
msgid "PLACE_TYPE_DUNGEON"
msgstr ""

#: models/place.py:25 models/place.py:35 models/place.py:45
#: tests/commands/testEnter.py:36 tests/commands/testEnter.py:41
#: tests/commands/testExit.py:35 tests/commands/testExit.py:40
msgid "ERROR_UNKNOWN_PLACE_TYPE"
msgstr ""

#: models/place.py:96
msgid "ERROR_PLACE_GENERATION"
msgstr ""

#: models/player.py:33
msgid "ERROR_CONNECT_INVALID_CREDENTIALS"
msgstr ""

#: tests/commands/testOpen.py:70 tests/commands/testOpen.py:82
#: tests/commands/testOpen.py:103 tests/commands/testOpen.py:111
msgid "ERROR_OPEN_INVALID_INDEX"
msgstr ""
