# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-04-07 16:44+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: CLI/main.py:57
msgid "CHOICE_QUESTION"
msgstr ""

#: CLI/main.py:57
msgid "MAIN_MENU_TITLE"
msgstr ""

#: CLI/main.py:58
msgid "CHOICE_LOAD_GAME"
msgstr ""

#: CLI/main.py:58
msgid "CHOICE_NEW_GAME"
msgstr ""

#: CLI/main.py:66
msgid "SAVED_GAME_MENU_TITLE"
msgstr ""

#: CLI/main.py:67
msgid "SAVED_GAME_CHOICE_QUESTION"
msgstr ""

#: CLI/main.py:78
#, python-brace-format
msgid "OVERWRITE_SAVEDGAME_QUESTION_{choices}"
msgstr ""

#: CLI/main.py:95
msgid "EMPTY_SAVED_GAME"
msgstr ""

#: CLI/main.py:100
#, python-brace-format
msgid "SAVED_GAME_INFO_{login}"
msgstr ""

#: CLI/main.py:105
msgid "LOGIN_PROMPT"
msgstr ""

#: CLI/main.py:108 core/commands/createPlayer.py:16
#: tests/core/commands/testCreatePlayer.py:46
#: tests/core/commands/testCreatePlayer.py:52
msgid "ERROR_SIGNUP_LOGIN_ALREADY_USED"
msgstr ""

#: CLI/main.py:114
msgid "GENDER_PROMPT"
msgstr ""

#: CLI/main.py:114
msgid "GENDER_SELECTION"
msgstr ""

#: CLI/main.py:127
msgid "SPECIES_PROMPT"
msgstr ""

#: CLI/main.py:127
msgid "SPECIES_SELECTION"
msgstr ""

#: CLI/main.py:136
msgid "GAME_OVER_TEXT"
msgstr ""

#: CLI/main.py:212
msgid "COMMAND_PROMPT"
msgstr ""

#: CLI/main.py:231
msgid "ANSWER_NO"
msgstr ""

#: CLI/main.py:231 CLI/main.py:236
msgid "ANSWER_YES"
msgstr ""

#: core/Rpg.py:37 tests/core/testRpg.py:24
msgid "ERROR_UNKNOWN_SELECTED_WORLD"
msgstr ""

#: core/Rpg.py:49 tests/core/testRpg.py:31
msgid "ERROR_RRPG_INIT_INVALID_SAVED_GAME_ID"
msgstr ""

#: core/Rpg.py:59 tests/core/testRpg.py:38
msgid "ERROR_SAVED_GAME_NEEDED_TO_INIT_PLAYER"
msgstr ""

#: core/Rpg.py:65 tests/core/testRpg.py:46
msgid "ERROR_NON_EMPTY_SAVED_GAME_NEEDED_TO_INIT_PLAYER"
msgstr ""

#: core/Rpg.py:72 tests/core/testRpg.py:64
msgid "ERROR_INVALID_FORMAT_ACTION"
msgstr ""

#: core/command_factory.py:42 core/commands/help.py:38
#: tests/core/commands/testHelp.py:24 tests/core/commands/testHelp.py:79
#: tests/core/commands/testLook.py:11 tests/core/commands/testLook.py:37
#: tests/core/commands/testLook.py:54 tests/core/commands/testLook.py:59
#: tests/core/commands/testLook.py:64 tests/core/commands/testLook.py:73
#: tests/core/commands/testLook.py:78 tests/core/commands/testLook.py:83
#: tests/core/commands/testLook.py:88 tests/core/commands/testLook.py:96
#: tests/core/commands/testLook.py:101 tests/core/commands/testLook.py:106
#: tests/core/commands/testLook.py:111 tests/core/commands/testLook.py:117
#: tests/core/commands/testLook.py:122 tests/core/commands/testLook.py:130
#: tests/core/commands/testLook.py:135 tests/core/commands/testLook.py:140
#: tests/core/commands/testLook.py:149 tests/core/commands/testLook.py:158
#: tests/core/commands/testLook.py:167 tests/core/commands/testSave.py:49
#: tests/core/commands/testSave.py:66 tests/core/commands/testSave.py:85
#: tests/core/commands/testSave.py:104 tests/core/commands/testSave.py:191
#: tests/core/commands/testSave.py:203 tests/core/commands/testSave.py:223
#: tests/core/commands/testSave.py:226 tests/core/commands/testTake.py:147
msgid "LOOK_COMMAND"
msgstr ""

#: core/command_factory.py:43 core/commands/help.py:22
#: tests/core/commands/testHelp.py:16 tests/core/commands/testHelp.py:63
#: tests/core/commands/testTalk.py:11 tests/core/commands/testTalk.py:16
#: tests/core/commands/testTalk.py:21 tests/core/commands/testTalk.py:26
#: tests/core/commands/testTalk.py:31 tests/core/commands/testTalk.py:36
#: tests/core/commands/testTalk.py:41 tests/core/commands/testTalk.py:46
#: tests/core/commands/testTalk.py:51
msgid "TALK_COMMAND"
msgstr ""

#: core/command_factory.py:44 core/commands/help.py:26
#: tests/core/commands/testAttack.py:25 tests/core/commands/testAttack.py:27
#: tests/core/commands/testAttack.py:31 tests/core/commands/testAttack.py:33
#: tests/core/commands/testEnter.py:21 tests/core/commands/testEnter.py:28
#: tests/core/commands/testHelp.py:18 tests/core/commands/testHelp.py:67
#: tests/core/commands/testLook.py:145 tests/core/commands/testLook.py:147
#: tests/core/commands/testLook.py:154 tests/core/commands/testLook.py:156
#: tests/core/commands/testLook.py:163 tests/core/commands/testLook.py:165
#: tests/core/commands/testMove.py:11 tests/core/commands/testMove.py:16
#: tests/core/commands/testMove.py:21 tests/core/commands/testMove.py:26
#: tests/core/commands/testMove.py:31 tests/core/commands/testMove.py:36
#: tests/core/commands/testMove.py:41 tests/core/commands/testMove.py:43
#: tests/core/commands/testMove.py:49 tests/core/commands/testMove.py:51
#: tests/core/commands/testMove.py:56 tests/core/commands/testMove.py:58
#: tests/core/commands/testMove.py:60 tests/core/commands/testMove.py:66
#: tests/core/commands/testMove.py:68 tests/core/commands/testMove.py:70
#: tests/core/commands/testMove.py:75 tests/core/commands/testMove.py:77
#: tests/core/commands/testMove.py:79 tests/core/commands/testMove.py:85
#: tests/core/commands/testMove.py:87 tests/core/commands/testMove.py:89
#: tests/core/commands/testMove.py:94 tests/core/commands/testMove.py:99
#: tests/core/commands/testSave.py:186 tests/core/commands/testSave.py:196
#: tests/core/commands/testSave.py:208 tests/core/commands/testSave.py:210
msgid "MOVE_COMMAND"
msgstr ""

#: core/command_factory.py:45 core/commands/help.py:30
#: tests/core/commands/testEnter.py:11 tests/core/commands/testEnter.py:16
#: tests/core/commands/testEnter.py:23 tests/core/commands/testEnter.py:30
#: tests/core/commands/testEnter.py:35 tests/core/commands/testEnter.py:40
#: tests/core/commands/testEnter.py:45 tests/core/commands/testEnter.py:47
#: tests/core/commands/testEnter.py:52 tests/core/commands/testEnter.py:54
#: tests/core/commands/testEnter.py:59 tests/core/commands/testEnter.py:64
#: tests/core/commands/testEnter.py:69 tests/core/commands/testEnter.py:74
#: tests/core/commands/testExit.py:50 tests/core/commands/testExit.py:57
#: tests/core/commands/testHelp.py:20 tests/core/commands/testHelp.py:71
msgid "ENTER_COMMAND"
msgstr ""

#: core/command_factory.py:46 core/commands/help.py:34
#: tests/core/commands/testExit.py:10 tests/core/commands/testExit.py:15
#: tests/core/commands/testExit.py:20 tests/core/commands/testExit.py:25
#: tests/core/commands/testExit.py:30 tests/core/commands/testExit.py:35
#: tests/core/commands/testExit.py:40 tests/core/commands/testExit.py:45
#: tests/core/commands/testExit.py:52 tests/core/commands/testExit.py:59
#: tests/core/commands/testHelp.py:22 tests/core/commands/testHelp.py:75
msgid "EXIT_COMMAND"
msgstr ""

#: core/command_factory.py:47 core/commands/help.py:51
#: tests/core/commands/testDrop.py:48 tests/core/commands/testDrop.py:60
#: tests/core/commands/testDrop.py:114 tests/core/commands/testDrop.py:121
#: tests/core/commands/testDrop.py:128 tests/core/commands/testDrop.py:135
#: tests/core/commands/testDrop.py:143 tests/core/commands/testDrop.py:150
#: tests/core/commands/testDrop.py:157 tests/core/commands/testDrop.py:164
#: tests/core/commands/testDrop.py:171 tests/core/commands/testDrop.py:181
#: tests/core/commands/testDrop.py:192 tests/core/commands/testDrop.py:199
#: tests/core/commands/testDrop.py:206 tests/core/commands/testDrop.py:213
#: tests/core/commands/testDrop.py:220 tests/core/commands/testDrop.py:227
#: tests/core/commands/testDrop.py:234 tests/core/commands/testDrop.py:241
#: tests/core/commands/testDrop.py:248 tests/core/commands/testDrop.py:255
#: tests/core/commands/testDrop.py:262 tests/core/commands/testDrop.py:269
#: tests/core/commands/testHelp.py:31 tests/core/commands/testHelp.py:91
#: tests/core/commands/testInventory.py:21
#: tests/core/commands/testInventory.py:28 tests/core/commands/testSave.py:41
#: tests/core/commands/testSave.py:58 tests/core/commands/testSave.py:75
#: tests/core/commands/testSave.py:94 tests/core/commands/testSave.py:112
#: tests/core/commands/testSave.py:132 tests/core/commands/testSave.py:149
#: tests/core/commands/testSave.py:171 tests/core/commands/testSave.py:212
#: tests/core/commands/testTake.py:12 tests/core/commands/testTake.py:17
#: tests/core/commands/testTake.py:22 tests/core/commands/testTake.py:27
#: tests/core/commands/testTake.py:32 tests/core/commands/testTake.py:37
#: tests/core/commands/testTake.py:43 tests/core/commands/testTake.py:48
#: tests/core/commands/testTake.py:53 tests/core/commands/testTake.py:58
#: tests/core/commands/testTake.py:63 tests/core/commands/testTake.py:68
#: tests/core/commands/testTake.py:73 tests/core/commands/testTake.py:78
#: tests/core/commands/testTake.py:84 tests/core/commands/testTake.py:89
#: tests/core/commands/testTake.py:94 tests/core/commands/testTake.py:99
#: tests/core/commands/testTake.py:105 tests/core/commands/testTake.py:110
#: tests/core/commands/testTake.py:115 tests/core/commands/testTake.py:120
#: tests/core/commands/testTake.py:125 tests/core/commands/testTake.py:128
#: tests/core/commands/testTake.py:133 tests/core/commands/testTake.py:135
#: tests/core/commands/testTake.py:138 tests/core/commands/testTake.py:144
#: tests/core/commands/testTake.py:153 tests/core/commands/testTake.py:158
#: tests/core/commands/testTake.py:163 tests/core/commands/testTake.py:168
#: tests/core/commands/testTake.py:173 tests/core/commands/testTake.py:178
#: tests/core/commands/testTake.py:183 tests/core/commands/testTake.py:188
#: tests/core/commands/testTake.py:193 tests/core/commands/testTake.py:198
#: tests/core/commands/testTake.py:203
msgid "TAKE_COMMAND"
msgstr ""

#: core/command_factory.py:48 core/commands/help.py:61
#: tests/core/commands/testDrop.py:14 tests/core/commands/testDrop.py:23
#: tests/core/commands/testDrop.py:32 tests/core/commands/testDrop.py:41
#: tests/core/commands/testDrop.py:53 tests/core/commands/testDrop.py:65
#: tests/core/commands/testDrop.py:73 tests/core/commands/testDrop.py:78
#: tests/core/commands/testDrop.py:83 tests/core/commands/testDrop.py:88
#: tests/core/commands/testDrop.py:93 tests/core/commands/testDrop.py:98
#: tests/core/commands/testDrop.py:103 tests/core/commands/testDrop.py:108
#: tests/core/commands/testDrop.py:116 tests/core/commands/testDrop.py:123
#: tests/core/commands/testDrop.py:130 tests/core/commands/testDrop.py:137
#: tests/core/commands/testDrop.py:145 tests/core/commands/testDrop.py:152
#: tests/core/commands/testDrop.py:159 tests/core/commands/testDrop.py:166
#: tests/core/commands/testDrop.py:173 tests/core/commands/testDrop.py:176
#: tests/core/commands/testDrop.py:183 tests/core/commands/testDrop.py:186
#: tests/core/commands/testDrop.py:194 tests/core/commands/testDrop.py:201
#: tests/core/commands/testDrop.py:208 tests/core/commands/testDrop.py:215
#: tests/core/commands/testDrop.py:222 tests/core/commands/testDrop.py:229
#: tests/core/commands/testDrop.py:236 tests/core/commands/testDrop.py:243
#: tests/core/commands/testDrop.py:250 tests/core/commands/testDrop.py:257
#: tests/core/commands/testDrop.py:264 tests/core/commands/testDrop.py:271
#: tests/core/commands/testHelp.py:39 tests/core/commands/testHelp.py:95
msgid "DROP_COMMAND"
msgstr ""

#: core/command_factory.py:49 core/commands/help.py:42
#: tests/core/commands/testHelp.py:26 tests/core/commands/testHelp.py:83
#: tests/core/commands/testInventory.py:11
#: tests/core/commands/testInventory.py:16
#: tests/core/commands/testInventory.py:23
#: tests/core/commands/testInventory.py:30 tests/core/commands/testSave.py:23
#: tests/core/commands/testSave.py:33 tests/core/commands/testSave.py:46
#: tests/core/commands/testSave.py:63 tests/core/commands/testSave.py:82
#: tests/core/commands/testSave.py:101 tests/core/commands/testSave.py:117
#: tests/core/commands/testSave.py:137 tests/core/commands/testSave.py:156
#: tests/core/commands/testSave.py:178 tests/core/commands/testSave.py:220
msgid "INVENTORY_COMMAND"
msgstr ""

#: core/command_factory.py:50 core/commands/help.py:42
#: tests/core/commands/testHelp.py:26 tests/core/commands/testHelp.py:83
msgid "INVENTORY_SHORT_COMMAND"
msgstr ""

#: core/command_factory.py:51 core/commands/help.py:70
#: tests/core/commands/testHelp.py:46 tests/core/commands/testHelp.py:99
#: tests/core/commands/testStats.py:12 tests/core/commands/testStats.py:35
msgid "STATS_COMMAND"
msgstr ""

#: core/command_factory.py:52 core/commands/help.py:82
#: tests/core/commands/testHelp.py:13 tests/core/commands/testHelp.py:52
#: tests/core/commands/testHelp.py:59 tests/core/commands/testHelp.py:111
msgid "HELP_COMMAND"
msgstr ""

#: core/command_factory.py:53 core/commands/help.py:46
#: tests/core/commands/testHelp.py:28 tests/core/commands/testHelp.py:87
#: tests/core/commands/testOpen.py:11 tests/core/commands/testOpen.py:16
#: tests/core/commands/testOpen.py:21 tests/core/commands/testOpen.py:26
#: tests/core/commands/testOpen.py:31 tests/core/commands/testOpen.py:36
#: tests/core/commands/testOpen.py:41 tests/core/commands/testOpen.py:46
#: tests/core/commands/testOpen.py:51 tests/core/commands/testOpen.py:60
#: tests/core/commands/testOpen.py:65 tests/core/commands/testOpen.py:69
#: tests/core/commands/testOpen.py:77 tests/core/commands/testOpen.py:81
#: tests/core/commands/testOpen.py:89 tests/core/commands/testOpen.py:98
#: tests/core/commands/testOpen.py:102 tests/core/commands/testOpen.py:106
#: tests/core/commands/testOpen.py:110 tests/core/commands/testOpen.py:114
#: tests/core/commands/testSave.py:120 tests/core/commands/testSave.py:140
#: tests/core/commands/testSave.py:159 tests/core/commands/testSave.py:181
msgid "OPEN_COMMAND"
msgstr ""

#: core/command_factory.py:54 core/commands/help.py:78
#: tests/core/commands/testHelp.py:50 tests/core/commands/testHelp.py:107
#: tests/core/commands/testSave.py:18 tests/core/commands/testSave.py:28
#: tests/core/commands/testSave.py:77 tests/core/commands/testSave.py:96
#: tests/core/commands/testSave.py:151 tests/core/commands/testSave.py:173
#: tests/core/commands/testSave.py:198 tests/core/commands/testSave.py:214
msgid "SAVE_COMMAND"
msgstr ""

#: core/command_factory.py:55 core/commands/help.py:74
#: tests/core/commands/testAttack.py:37 tests/core/commands/testAttack.py:42
#: tests/core/commands/testAttack.py:49 tests/core/commands/testAttack.py:62
#: tests/core/commands/testAttack.py:88 tests/core/commands/testAttack.py:101
#: tests/core/commands/testAttack.py:128 tests/core/commands/testAttack.py:144
#: tests/core/commands/testHelp.py:48 tests/core/commands/testHelp.py:103
msgid "ATTACK_COMMAND"
msgstr ""

#: core/command_factory.py:79 core/commands/help.py:86
#: tests/core/commands/testHelp.py:54 tests/core/commands/testHelp.py:115
#: tests/core/commands/testQuit.py:11 tests/core/commands/testQuit.py:16
msgid "QUIT_COMMAND"
msgstr ""

#: core/command_factory.py:79 core/commands/help.py:86
#: tests/core/commands/testHelp.py:54 tests/core/commands/testHelp.py:115
msgid "QUIT_SHORT_COMMAND"
msgstr ""

#: core/command_factory.py:86
msgid "ERROR_DENIED_COMMAND_WHILE_FIGHTING"
msgstr ""

#: core/command_factory.py:93 tests/core/testRpg.py:69
#: tests/core/testRpg.py:74
msgid "ERROR_UNKNOWN_COMMAND"
msgstr ""

#: core/commands/attack.py:19 tests/core/commands/testAttack.py:39
#: tests/core/commands/testAttack.py:44
msgid "ERROR_FIGHT_NOT_FIGHTING"
msgstr ""

#: core/commands/attack.py:30 tests/core/commands/testAttack.py:54
#: tests/core/commands/testAttack.py:93 tests/core/commands/testAttack.py:135
#, python-brace-format
msgid "ATTACK_CONFIRM_PLAYER_TO_ENEMY_{enemy}_{damages}"
msgstr ""

#: core/commands/attack.py:31 core/commands/move.py:74
#: tests/core/commands/testAttack.py:55 tests/core/commands/testAttack.py:136
#, python-brace-format
msgid "ATTACK_CONFIRM_ENEMY_TO_PLAYER_{enemy}_{damages}"
msgstr ""

#: core/commands/attack.py:32 tests/core/commands/testAttack.py:94
#, python-brace-format
msgid "ATTACK_VICTORY_{enemy}"
msgstr ""

#: core/commands/attack.py:33 tests/core/commands/testAttack.py:137
#, python-brace-format
msgid "ATTACK_LOST_{enemy}"
msgstr ""

#: core/commands/createPlayer.py:10 tests/core/commands/testCreatePlayer.py:34
#: tests/core/commands/testCreatePlayer.py:40
msgid "ERROR_SIGNUP_NOT_ENOUGH_ARGUMENTS"
msgstr ""

#: core/commands/createPlayer.py:20 tests/core/commands/testCreatePlayer.py:58
#: tests/core/commands/testCreatePlayer.py:64
msgid "ERROR_SIGNUP_INVALID_GENDER"
msgstr ""

#: core/commands/createPlayer.py:24 tests/core/commands/testCreatePlayer.py:70
#: tests/core/commands/testCreatePlayer.py:76
msgid "ERROR_SIGNUP_INVALID_SPECIES"
msgstr ""

#: core/commands/createPlayer.py:43 tests/core/commands/testCreatePlayer.py:82
msgid "PLAYER_CREATION_CONFIRMATION"
msgstr ""

#: core/commands/drop.py:20 tests/core/commands/testDrop.py:75
#: tests/core/commands/testDrop.py:80 tests/core/commands/testDrop.py:85
#: tests/core/commands/testDrop.py:90
msgid "ERROR_DROP_NO_ITEM_GIVEN"
msgstr ""

#: core/commands/drop.py:22 tests/core/commands/testDrop.py:34
#: tests/core/commands/testDrop.py:43
msgid "ERROR_DROP_TOO_LOW_QUANTITY"
msgstr ""

#: core/commands/drop.py:24 tests/core/commands/testDrop.py:16
#: tests/core/commands/testDrop.py:25
msgid "ERROR_DROP_INVALID_FORMAT_QUANTITY"
msgstr ""

#: core/commands/drop.py:26 tests/core/commands/testDrop.py:161
#: tests/core/commands/testDrop.py:168
msgid "ERROR_DROP_INVALID_CONTAINER_INDEX"
msgstr ""

#: core/commands/drop.py:40 tests/core/commands/testDrop.py:95
#: tests/core/commands/testDrop.py:100
msgid "ERROR_DROP_UNKNOWN_ITEM"
msgstr ""

#: core/commands/drop.py:45 tests/core/commands/testDrop.py:105
#: tests/core/commands/testDrop.py:110
msgid "ERROR_DROP_ITEM_NOT_AVAILABLE"
msgstr ""

#: core/commands/drop.py:47 tests/core/commands/testDrop.py:55
#: tests/core/commands/testDrop.py:67
#, python-format
msgid "ERROR_DROP_QUANTITY_TOO_HIGH_%s"
msgstr ""

#: core/commands/drop.py:62 tests/core/commands/testDrop.py:196
#: tests/core/commands/testDrop.py:210 tests/core/commands/testDrop.py:224
#: tests/core/commands/testDrop.py:238 tests/core/commands/testDrop.py:252
#: tests/core/commands/testDrop.py:266
#, python-format
msgid "DROP_CONFIRMATION_%(quantity)s_%(name)s"
msgstr ""

#: core/commands/enter.py:21 tests/core/commands/testEnter.py:13
#: tests/core/commands/testEnter.py:18
msgid "ERROR_ENTER_NO_PLACE_GIVEN"
msgstr ""

#: core/commands/enter.py:27 core/commands/exit.py:27
#: tests/core/commands/testEnter.py:25 tests/core/commands/testEnter.py:32
#: tests/core/commands/testEnter.py:49 tests/core/commands/testEnter.py:56
#: tests/core/commands/testExit.py:22 tests/core/commands/testExit.py:27
#: tests/core/commands/testExit.py:42 tests/core/commands/testExit.py:47
msgid "ERROR_ENTER_PLACE_NOT_AVAILABLE"
msgstr ""

#: core/commands/enter.py:32 tests/core/commands/testEnter.py:61
#: tests/core/commands/testEnter.py:66 tests/core/commands/testEnter.py:71
#: tests/core/commands/testEnter.py:76
msgid "ENTER_CONFIRMATION"
msgstr ""

#: core/commands/exit.py:21 tests/core/commands/testExit.py:12
#: tests/core/commands/testExit.py:17
msgid "ERROR_EXIT_NO_PLACE_GIVEN"
msgstr ""

#: core/commands/exit.py:30 tests/core/commands/testExit.py:54
#: tests/core/commands/testExit.py:61
msgid "EXIT_CONFIRMATION"
msgstr ""

#: core/commands/help.py:22 tests/core/commands/testHelp.py:16
#: tests/core/commands/testHelp.py:63
msgid "CHARACTER_TOKEN"
msgstr ""

#: core/commands/help.py:22 tests/core/commands/testHelp.py:16
#: tests/core/commands/testHelp.py:63
msgid "SENTENCE_TOKEN"
msgstr ""

#: core/commands/help.py:23 tests/core/commands/testHelp.py:17
#: tests/core/commands/testHelp.py:64
msgid "TALK_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:27 tests/core/commands/testHelp.py:19
#: tests/core/commands/testHelp.py:68
msgid "MOVE_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:31 tests/core/commands/testHelp.py:21
#: tests/core/commands/testHelp.py:72
msgid "ENTER_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:35 tests/core/commands/testHelp.py:23
#: tests/core/commands/testHelp.py:76
msgid "EXIT_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:39 tests/core/commands/testHelp.py:25
#: tests/core/commands/testHelp.py:80
msgid "LOOK_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:43 tests/core/commands/testHelp.py:27
#: tests/core/commands/testHelp.py:84
msgid "INVENTORY_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:46 core/commands/help.py:55 core/commands/help.py:65
#: tests/core/commands/testHelp.py:28 tests/core/commands/testHelp.py:35
#: tests/core/commands/testHelp.py:43 tests/core/commands/testHelp.py:87
#: tests/core/commands/testHelp.py:91 tests/core/commands/testHelp.py:95
msgid "CONTAINER_INDEX_TOKEN"
msgstr ""

#: core/commands/help.py:46 core/commands/help.py:54 core/commands/help.py:64
#: tests/core/commands/testHelp.py:28 tests/core/commands/testHelp.py:34
#: tests/core/commands/testHelp.py:42 tests/core/commands/testHelp.py:87
#: tests/core/commands/testHelp.py:91 tests/core/commands/testHelp.py:95
msgid "CONTAINER_TOKEN"
msgstr ""

#: core/commands/help.py:47 tests/core/commands/testHelp.py:29
#: tests/core/commands/testHelp.py:88
msgid "OPEN_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:52 core/commands/help.py:62
#: tests/core/commands/testHelp.py:32 tests/core/commands/testHelp.py:40
#: tests/core/commands/testHelp.py:91 tests/core/commands/testHelp.py:95
msgid "QUANTITY_TOKEN"
msgstr ""

#: core/commands/help.py:53 core/commands/help.py:63
#: tests/core/commands/testHelp.py:33 tests/core/commands/testHelp.py:41
#: tests/core/commands/testHelp.py:91 tests/core/commands/testHelp.py:95
msgid "ITEM_NAME_TOKEN"
msgstr ""

#: core/commands/help.py:57 tests/core/commands/testHelp.py:37
#: tests/core/commands/testHelp.py:92
msgid "TAKE_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:67 tests/core/commands/testHelp.py:45
#: tests/core/commands/testHelp.py:96
msgid "DROP_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:71 tests/core/commands/testHelp.py:47
#: tests/core/commands/testHelp.py:100
msgid "STATS_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:75 tests/core/commands/testHelp.py:49
#: tests/core/commands/testHelp.py:104
msgid "ATTACK_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:79 tests/core/commands/testHelp.py:51
#: tests/core/commands/testHelp.py:108
msgid "SAVE_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:83 tests/core/commands/testHelp.py:53
#: tests/core/commands/testHelp.py:112
msgid "HELP_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:87 tests/core/commands/testHelp.py:55
#: tests/core/commands/testHelp.py:116
msgid "QUIT_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:92 tests/core/commands/testHelp.py:15
msgid "AVAILABLE_COMMANDS_TITLE"
msgstr ""

#: core/commands/inventory.py:27 tests/core/commands/testInventory.py:13
#: tests/core/commands/testSave.py:25 tests/core/commands/testSave.py:48
#: tests/core/commands/testSave.py:119
msgid "INVENTORY_EMPTY"
msgstr ""

#: core/commands/item_interaction.py:50 tests/core/commands/testDrop.py:132
#: tests/core/commands/testDrop.py:139 tests/core/commands/testOpen.py:23
#: tests/core/commands/testOpen.py:28 tests/core/commands/testTake.py:96
#: tests/core/commands/testTake.py:101
msgid "ERROR_CONTAINER_NOT_AVAILABLE"
msgstr ""

#: core/commands/item_interaction.py:56 tests/core/commands/testDrop.py:175
#: tests/core/commands/testDrop.py:178 tests/core/commands/testDrop.py:185
#: tests/core/commands/testDrop.py:188 tests/core/commands/testOpen.py:67
#: tests/core/commands/testOpen.py:79 tests/core/commands/testOpen.py:100
#: tests/core/commands/testOpen.py:108 tests/core/commands/testTake.py:127
#: tests/core/commands/testTake.py:130 tests/core/commands/testTake.py:137
#: tests/core/commands/testTake.py:140
#, python-format
msgid "ERROR_OUT_OF_RANGE_ITEM_CONTAINER_INDEX_%d"
msgstr ""

#: core/commands/item_interaction.py:59 tests/core/commands/testDrop.py:147
#: tests/core/commands/testDrop.py:154 tests/core/commands/testOpen.py:43
#: tests/core/commands/testOpen.py:48 tests/core/commands/testTake.py:107
#: tests/core/commands/testTake.py:112
msgid "ERROR_MULTIPLE_CONTAINERS_AVAILABLE"
msgstr ""

#: core/commands/look.py:20 tests/core/commands/testLook.py:64
#: tests/core/commands/testLook.py:73 tests/core/commands/testLook.py:167
#: tests/core/commands/testSave.py:191 tests/core/commands/testSave.py:203
#: tests/core/commands/testSave.py:226
msgid "LOOK_REGION_PARAM"
msgstr ""

#: core/commands/look.py:21 tests/core/commands/testLook.py:135
#: tests/core/commands/testLook.py:140 tests/core/commands/testLook.py:149
#: tests/core/commands/testLook.py:158
msgid "LOOK_FIGHT_PARAM"
msgstr ""

#: core/commands/look.py:22 tests/core/commands/testLook.py:78
#: tests/core/commands/testLook.py:83
msgid "LOOK_CHARACTERS_PARAM"
msgstr ""

#: core/commands/look.py:23 tests/core/commands/testLook.py:88
#: tests/core/commands/testLook.py:96
msgid "LOOK_DIRECTIONS_PARAM"
msgstr ""

#: core/commands/look.py:24 tests/core/commands/testLook.py:101
#: tests/core/commands/testLook.py:106
msgid "LOOK_PLACES_PARAM"
msgstr ""

#: core/commands/look.py:25 tests/core/commands/testLook.py:111
#: tests/core/commands/testLook.py:117 tests/core/commands/testSave.py:49
#: tests/core/commands/testSave.py:66 tests/core/commands/testSave.py:85
#: tests/core/commands/testSave.py:104 tests/core/commands/testSave.py:223
#: tests/core/commands/testTake.py:147
msgid "LOOK_OBJECTS_PARAM"
msgstr ""

#: core/commands/look.py:26 tests/core/commands/testLook.py:122
#: tests/core/commands/testLook.py:130
msgid "LOOK_CONTAINERS_PARAM"
msgstr ""

#: core/commands/look.py:38 tests/core/commands/testLook.py:56
#: tests/core/commands/testLook.py:61
msgid "ERROR_LOOK_UNKNOWN_SECTION"
msgstr ""

#: core/commands/look.py:114 tests/core/commands/testLook.py:14
#: tests/core/commands/testLook.py:67
#, python-format
msgid "CURRENT_REGION_%s"
msgstr ""

#: core/commands/look.py:117 tests/core/commands/testLook.py:15
#: tests/core/commands/testLook.py:68
msgid "AREA_HAS_SAVE_POINT"
msgstr ""

#: core/commands/look.py:121 tests/core/commands/testLook.py:151
#, python-format
msgid "CURRENTLY_FIGHTING_%s"
msgstr ""

#: core/commands/look.py:125 tests/core/commands/testLook.py:17
#: tests/core/commands/testLook.py:80
msgid "PRESENT_CHARACTERS"
msgstr ""

#: core/commands/look.py:132 tests/core/commands/testLook.py:20
#: tests/core/commands/testLook.py:91
msgid "AVAILABLE_DIRECTIONS"
msgstr ""

#: core/commands/look.py:139 tests/core/commands/testLook.py:23
#: tests/core/commands/testLook.py:103
msgid "AVAILABLE_PLACES"
msgstr ""

#: core/commands/look.py:146 tests/core/commands/testLook.py:27
#: tests/core/commands/testLook.py:113 tests/core/commands/testSave.py:51
#: tests/core/commands/testSave.py:87 tests/core/commands/testTake.py:149
msgid "AVAILABLE_ITEMS"
msgstr ""

#: core/commands/look.py:153 tests/core/commands/testLook.py:30
#: tests/core/commands/testLook.py:124
msgid "AVAILABLE_ITEMS_CONTAINERS"
msgstr ""

#: core/commands/move.py:21 tests/core/commands/testMove.py:13
#: tests/core/commands/testMove.py:18
msgid "ERROR_MOVE_NO_DIRECTION_GIVEN"
msgstr ""

#: core/commands/move.py:25 tests/core/commands/testMove.py:23
#: tests/core/commands/testMove.py:28
#, python-format
msgid "ERROR_MOVE_INVALID_DIRECTION_%s"
msgstr ""

#: core/commands/move.py:32 tests/core/commands/testMove.py:33
#: tests/core/commands/testMove.py:38
msgid "ERROR_MOVE_DIRECTION_NOT_AVAILABLE"
msgstr ""

#: core/commands/move.py:41 tests/core/commands/testMove.py:82
#: tests/core/commands/testMove.py:91
msgid "ERROR_FLEE_FIGHT_FAILS"
msgstr ""

#: core/commands/move.py:71 tests/core/commands/testMove.py:63
#, python-brace-format
msgid "MOVE_CONFIRMATION_{direction}_FIGHT_FLEE_{enemy}"
msgstr ""

#: core/commands/move.py:72 tests/core/commands/testMove.py:46
#, python-brace-format
msgid "MOVE_CONFIRMATION_{direction}_FIGHT_{enemy}"
msgstr ""

#: core/commands/move.py:73
#, python-brace-format
msgid "MOVE_CONFIRMATION_{direction}_AMBUSH_{enemy}"
msgstr ""

#: core/commands/move.py:90 tests/core/commands/testMove.py:96
#, python-format
msgid "MOVE_CONFIRMATION_%s"
msgstr ""

#: core/commands/open.py:18 tests/core/commands/testOpen.py:13
#: tests/core/commands/testOpen.py:18
msgid "ERROR_OPEN_NO_CONTAINER_PROVIDED"
msgstr ""

#: core/commands/open.py:44 tests/core/commands/testOpen.py:54
#: tests/core/commands/testOpen.py:72 tests/core/commands/testOpen.py:84
#: tests/core/commands/testOpen.py:92 tests/core/commands/testSave.py:123
#: tests/core/commands/testSave.py:162
#, python-format
msgid "ITEMS_IN_CONTAINER_%s"
msgstr ""

#: core/commands/save.py:25 tests/core/commands/testSave.py:216
msgid "ERROR_SAVE_NO_SAVE_POINT"
msgstr ""

#: core/commands/save.py:36
msgid "SAVE_CONFIRMATION_OK"
msgstr ""

#: core/commands/stats.py:31 tests/core/commands/testStats.py:15
msgid "STAT_CURRENT_HP"
msgstr ""

#: core/commands/stats.py:32 tests/core/commands/testStats.py:16
msgid "STAT_ATTACK"
msgstr ""

#: core/commands/stats.py:33 tests/core/commands/testStats.py:17
msgid "STAT_DEFENCE"
msgstr ""

#: core/commands/stats.py:34 tests/core/commands/testStats.py:19
msgid "STAT_SPEED"
msgstr ""

#: core/commands/stats.py:35 tests/core/commands/testStats.py:18
msgid "STAT_LUCK"
msgstr ""

#: core/commands/take.py:15 tests/core/commands/testTake.py:45
#: tests/core/commands/testTake.py:50 tests/core/commands/testTake.py:55
#: tests/core/commands/testTake.py:60
msgid "ERROR_TAKE_NO_ITEM_GIVEN"
msgstr ""

#: core/commands/take.py:17 tests/core/commands/testTake.py:24
#: tests/core/commands/testTake.py:29
msgid "ERROR_TAKE_TOO_LOW_QUANTITY"
msgstr ""

#: core/commands/take.py:19 tests/core/commands/testTake.py:14
#: tests/core/commands/testTake.py:19
msgid "ERROR_TAKE_INVALID_FORMAT_QUANTITY"
msgstr ""

#: core/commands/take.py:21 tests/core/commands/testTake.py:117
#: tests/core/commands/testTake.py:122
msgid "ERROR_TAKE_INVALID_CONTAINER_INDEX"
msgstr ""

#: core/commands/take.py:27 tests/core/commands/testTake.py:65
#: tests/core/commands/testTake.py:70
msgid "ERROR_TAKE_UNKNOWN_ITEM"
msgstr ""

#: core/commands/take.py:43 tests/core/commands/testTake.py:75
#: tests/core/commands/testTake.py:80
msgid "ERROR_TAKE_ITEM_NOT_AVAILABLE"
msgstr ""

#: core/commands/take.py:46 tests/core/commands/testTake.py:34
#: tests/core/commands/testTake.py:39
#, python-format
msgid "ERROR_TAKE_QUANTITY_TOO_HIGH_%s"
msgstr ""

#: core/commands/take.py:59 tests/core/commands/testTake.py:146
#: tests/core/commands/testTake.py:160 tests/core/commands/testTake.py:170
#: tests/core/commands/testTake.py:180 tests/core/commands/testTake.py:190
#: tests/core/commands/testTake.py:200
#, python-format
msgid "TAKE_CONFIRMATION_%(quantity)s_%(name)s"
msgstr ""

#: core/commands/talk.py:18 tests/core/commands/testTalk.py:13
#: tests/core/commands/testTalk.py:18
msgid "ERROR_TALK_NO_CHARACTER_GIVEN"
msgstr ""

#: core/commands/talk.py:20 tests/core/commands/testTalk.py:23
#: tests/core/commands/testTalk.py:28
msgid "ERROR_TALK_NO_SENTENCE_GIVEN"
msgstr ""

#: core/commands/talk.py:29 tests/core/commands/testTalk.py:33
#: tests/core/commands/testTalk.py:38
msgid "ERROR_TALK_UNKNOWN_CHARACTER"
msgstr ""

#: core/commands/talk.py:36 tests/core/commands/testTalk.py:43
msgid "ERROR_TALK_UNKNOWN_SENTENCE"
msgstr ""

#: models/area.py:21
msgid "DIRECTION_KEY_NORTH"
msgstr ""

#: models/area.py:22 tests/core/commands/testAttack.py:27
#: tests/core/commands/testLook.py:147 tests/core/commands/testLook.py:156
#: tests/core/commands/testMove.py:31 tests/core/commands/testMove.py:36
#: tests/core/commands/testMove.py:43 tests/core/commands/testMove.py:45
#: tests/core/commands/testMove.py:51 tests/core/commands/testMove.py:53
#: tests/core/commands/testMove.py:58 tests/core/commands/testMove.py:68
#: tests/core/commands/testMove.py:79 tests/core/commands/testMove.py:89
msgid "DIRECTION_KEY_EAST"
msgstr ""

#: models/area.py:23 tests/core/commands/testAttack.py:25
#: tests/core/commands/testAttack.py:31 tests/core/commands/testEnter.py:21
#: tests/core/commands/testEnter.py:28 tests/core/commands/testLook.py:21
#: tests/core/commands/testLook.py:40 tests/core/commands/testLook.py:92
#: tests/core/commands/testLook.py:98 tests/core/commands/testLook.py:145
#: tests/core/commands/testLook.py:154 tests/core/commands/testLook.py:163
#: tests/core/commands/testLook.py:165 tests/core/commands/testMove.py:41
#: tests/core/commands/testMove.py:49 tests/core/commands/testMove.py:56
#: tests/core/commands/testMove.py:66 tests/core/commands/testMove.py:75
#: tests/core/commands/testMove.py:85 tests/core/commands/testMove.py:94
#: tests/core/commands/testMove.py:96 tests/core/commands/testMove.py:99
#: tests/core/commands/testMove.py:101 tests/core/commands/testSave.py:186
#: tests/core/commands/testSave.py:196 tests/core/commands/testSave.py:208
#: tests/core/commands/testSave.py:210
msgid "DIRECTION_KEY_SOUTH"
msgstr ""

#: models/area.py:24 tests/core/commands/testAttack.py:33
#: tests/core/commands/testMove.py:60 tests/core/commands/testMove.py:62
#: tests/core/commands/testMove.py:70 tests/core/commands/testMove.py:72
#: tests/core/commands/testMove.py:77 tests/core/commands/testMove.py:81
#: tests/core/commands/testMove.py:87
msgid "DIRECTION_KEY_WEST"
msgstr ""

#: models/area.py:39
msgid "AREA_TYPE_DUNGEON"
msgstr ""

#: models/area.py:39
msgid "AREA_TYPE_LAND"
msgstr ""

#: models/item_container.py:43 tests/core/commands/testDrop.py:118
#: tests/core/commands/testDrop.py:125 tests/core/commands/testOpen.py:33
#: tests/core/commands/testOpen.py:38 tests/core/commands/testTake.py:86
#: tests/core/commands/testTake.py:91
msgid "ERROR_UNKNOWN_ITEM_CONTAINER_TYPE_LABEL"
msgstr ""

#: models/place.py:15 models/place.py:29 models/place.py:39 models/place.py:46
#: tests/core/commands/testEnter.py:23 tests/core/commands/testEnter.py:69
#: tests/core/commands/testEnter.py:74 tests/core/commands/testExit.py:20
#: tests/core/commands/testExit.py:25
msgid "PLACE_TYPE_CAVE"
msgstr ""

#: models/place.py:15 models/place.py:27 models/place.py:37 models/place.py:44
#: tests/core/commands/testEnter.py:45 tests/core/commands/testEnter.py:47
#: tests/core/commands/testEnter.py:52 tests/core/commands/testEnter.py:54
#: tests/core/commands/testEnter.py:59 tests/core/commands/testEnter.py:64
#: tests/core/commands/testExit.py:40 tests/core/commands/testExit.py:45
#: tests/core/commands/testExit.py:50 tests/core/commands/testExit.py:52
#: tests/core/commands/testExit.py:57 tests/core/commands/testExit.py:59
msgid "PLACE_TYPE_DUNGEON"
msgstr ""

#: models/place.py:25 models/place.py:35 tests/core/commands/testEnter.py:37
#: tests/core/commands/testEnter.py:42 tests/core/commands/testExit.py:32
#: tests/core/commands/testExit.py:37
msgid "ERROR_UNKNOWN_PLACE_TYPE"
msgstr ""

#: models/place.py:93
msgid "ERROR_PLACE_GENERATION"
msgstr ""

#: models/player.py:26 tests/core/testRpg.py:54
msgid "ERROR_CONNECT_INVALID_CREDENTIALS"
msgstr ""
